export const metadataContainer: string;
export const title: string;
export const promoSpectrumBar: string;
export const description: string;
export const ctaButton: string;
export const ctaButtonText: string;
export const logo: string;
export const logoDesktop: string;
export const logoMobile: string;
